accent = "#011627"
cursor = "#90a7b2"
foreground = "#403f53"
background = "#f6f6f6"
selection_foreground = "#403f53"
selection_background = "#d3e8f8"

color0 = "#403f53"
color1 = "#de3d3b"
color2 = "#08916a"
color3 = "#e0af02"
color4 = "#288ed7"
color5 = "#d6438a"
color6 = "#2aa298"
color7 = "#93a1a1"
color8 = "#697098"
color9 = "#e64d49"
color10 = "#08916a"
color11 = "#daaa01"
color12 = "#4876d6"
color13 = "#994cc3"
color14 = "#0c969b"
color15 = "#111111"
